# Generated by Django 4.1.1 on 2022-12-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(blank=True, max_length=3000)),
                ('about_image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='HomeCoverImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(blank=True)),
                ('image_name', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Initiatives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiative_id', models.CharField(blank=True, max_length=20)),
                ('initiative_name', models.CharField(blank=True, max_length=300)),
                ('coverimage', models.ImageField(blank=True, upload_to='')),
                ('introtext', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
