# Generated by Django 4.1.1 on 2022-12-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(blank=True)),
                ('image_name', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
