# Generated by Django 4.1.1 on 2022-12-27 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_patronages_team_vision'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadingTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, choices=[('1', 'For Competition and Mentoring Related Queries'), ('2', 'For Sponsorship Queries'), ('3', 'For Portal and Media Queries')], max_length=3000)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='heading',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, to='api.headingteam'),
        ),
    ]
