# Generated by Django 4.1.1 on 2022-12-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_headingteam_team_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headingteam',
            name='heading',
            field=models.CharField(blank=True, choices=[('1', 'For Competition and Mentoring Related Queries'), ('2', 'For Sponsorship Queries'), ('3', 'For Portal and Media Queries')], default='1', max_length=300),
        ),
    ]
