# Generated by Django 4.1.1 on 2022-12-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_headingteam_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headingteam',
            name='heading',
            field=models.CharField(blank=True, choices=[('For Competition and Mentoring Related Queries', 'For Competition and Mentoring Related Queries'), ('For Sponsorship Queries', 'For Sponsorship Queries'), ('For Portal and Media Queries', 'For Portal and Media Queries')], default='1', max_length=300),
        ),
    ]
