# Generated by Django 4.1.1 on 2022-12-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_headingteam_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headingteam',
            name='heading',
            field=models.CharField(blank=True, choices=[('Events & PR Head', 'Events & PR Head'), ('Marketing Head', 'Marketing Head'), ('Design Head', 'Design Head'), ('Technical & Web Head', 'Technical & Web Head'), ('Corporate Relations Head', 'Corporate Relations Head'), ('Media Head', 'Media Head'), ('Operations Head', 'Operations Head'), ('Overall Coordinator', 'Overall Coordinator')], default='1', max_length=300),
        ),
    ]
